sudo: required
services:
  - docker


before_install:
  - docker build -t srikanth787/reactfrontend:latest -f Dockerfile.dev .

script:
  - docker run srikanth787/reactfrontend:latest npm run test -- -- coverage


