sudo: required
services:
  - docker


before_install:
  - docker build -t srikanth787/reactfrontend:latest -f Dockerfile.dev .

script:
  - docker run srikanth787/reactfrontend:latest npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "elasticbeanstalk-us-west-2-430308303457"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "AWS_SECRET_KEY"


